# Config
rss: # link
favicon: https://tva1.sinaimg.cn/large/006y8mN6ly1g6sjqjrb9wj30jj0jjjss.jpg
blog_logo: https://tva1.sinaimg.cn/large/006y8mN6ly1g6sjqjrb9wj30jj0jjjss.jpg
header_image: https://tva1.sinaimg.cn/large/006y8mN6ly1g77gpw5lrfj31bt0u0qv6.jpg
bio: 想做一个会写码的挣钱机器
post_toc: true

# Keywords
keywords: hexo, casper, ghost, theme

# Menu
menu:
  HOME: /
  ABOUT: /about
  ARCHIVES: /archives
  # you can add here

# author
author_image: https://tva1.sinaimg.cn/large/006y8mN6ly1g77gqlmlvoj30u013xhdt.jpg
author_bio: 01不是包子脸啊
author_location:

# Social Links
social:
  weibo: https://weibo.com/2164694963/profile?rightmod=1&wvr=6&mod=personinfo
  github: https://github.com/linyi531
  twitter: https://twitter.com/nFywOCNPid75cl5
  # facebook: https://facebook
  telegram: https://www.instagram.com/linyi531/
  # bilibili:
  # youtube:
  # You only can use that I have added, I will keep adding

# Footer Links
footer_text:
  # title: link
  # 粤ICP备xxxxxxx号-x: http://www.miitbeian.gov.cn
  # 粤公网安备xxxxxxx号: http://www.beian.gov.cn

# Widget
widgets:
  recent_posts: true
  category: true
  tagcloud: true
  # This is a simple theme, I think 3 is enough.

# Post page fload header
floadheader: true

# Gallery
# https://github.com/sachinchoolur/lightgallery.js
lightgallery: true

# LazyLoad
# home page has enabled, this value is to post page
# https://github.com/dinbror/blazy
lazyload: true

# Local Search
local_search: true

# Comment
# https://valine.js.org
comment: true
valine:
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  appId: RKl7DjTGeDG8TMedBcYhiagz-gzGzoHsz
  appKey: pcwdBNPnrqDUcLyj3H0TaeHy
  placeholder: 爱我就留下评论吧～～ # comment box placeholder
  pageSize: 10 # pagination size
  avatar: mm # gravatar style

# PWA
# you need create a manifest.json file in hexo's source folder
manifest: false
service_workers: false

navColor: "3c484e"

# Baidu Push
baidu: false

# Google Analytics
googleAnalytics: true
GA_TRACKING_ID: UA-145838942-1
